spring:
  datasource:
    embedded-database-connection: h2
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  banner:
    charset: utf-8
  devtools:
    livereload:
      enabled: true
